name = "ts-chart-worker"
compatibility_date = "2025-07-11"
workers_dev = false
routes = [{ pattern = "d117.brightringsoftware.com", custom_domain = true }]
main = "ts-chart-worker.js"

[assets]
binding = "ASSETS"
